#if !canImport(ObjectiveC)
import XCTest

extension UnifiedLoggingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnifiedLoggingTests = [
        ("test_stubs", test_stubs),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(UnifiedLoggingTests.__allTests__UnifiedLoggingTests),
    ]
}
#endif
