#if !canImport(ObjectiveC)
import XCTest

extension UnifiedConsoleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnifiedConsoleTests = [
        ("test_stubs", test_stubs),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(UnifiedConsoleTests.__allTests__UnifiedConsoleTests),
    ]
}
#endif
